//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV_MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.TietHocs = new HashSet<TietHoc>();
            this.TietHocBus = new HashSet<TietHocBu>();
        }

        public int maLopHoc { get; set; }
        public Nullable<int> thu { get; set; }
        public Nullable<int> tietBatDau { get; set; }
        public Nullable<int> soTiet { get; set; }
        public string phong { get; set; }
        public string maLop { get; set; }
        public string maGiangVien { get; set; }
        public string maMonHoc { get; set; }

        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TietHoc> TietHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TietHocBu> TietHocBus { get; set; }

        public string NoiDung { get => "Thứ " + thu + " Tiết " + tietBatDau + " Phòng " + phong; }
        public string NoiDungLop { get => "Lớp " + maLop; }
    }
}
