//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV_MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LopHoc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LopHoc()
        {
            this.BuoiHocs = new HashSet<BuoiHoc>();
            this.BuoiHocBus = new HashSet<BuoiHocBu>();
        }
    
        public int Id { get; set; }
        public Nullable<int> thu { get; set; }
        public Nullable<int> tietBatDau { get; set; }
        public Nullable<int> soTiet { get; set; }
        public string maLop { get; set; }
        public Nullable<int> idGiangVien { get; set; }
        public Nullable<int> idMonHoc { get; set; }
        public Nullable<int> nhom { get; set; }
        public string tenPhong { get; set; }
        public Nullable<double> soTinChi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiHoc> BuoiHocs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuoiHocBu> BuoiHocBus { get; set; }
        public virtual GiangVien GiangVien { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
