//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV_MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinHoc
    {
        public System.DateTime ngayNhapHoc { get; set; }
        public Nullable<System.DateTime> ngayKetThuc { get; set; }
        public Nullable<int> soTietHoc { get; set; }
    }
}
