//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGV_MVVM.Model
{
    using System;
    using System.Collections.Generic;

    public partial class TietHocBu : TietHoc
    {

        public Nullable<int> tietBatDau { get; set; }


        public override int TietBatDau { get => tietBatDau == null ? 0 : tietBatDau.Value; }
        public virtual TietHoc TietHoc { get; set; }
        public override string TuanHocBu => TietHoc.Tuan + "";


    }
}
